server {
    listen 80;
    listen [::]:80;
    server_name sakay.online 112.207.129.64;
    server_tokens off;
    
    # Root for certbot files
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    # Proxy to your React app
    location / {
        proxy_pass http://sakay-client:80;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
